build: better error trap handler in verinc script

diff --git a/build/verinc b/build/verinc
--- a/build/verinc
+++ b/build/verinc
@@ -1,9 +1,7 @@
 #!/bin/bash
 
 function handleErr {
-	SNAME=$(basename "$BASH_SOURCE")
-	echo "$SNAME: Error on line $1"
-	exit 1
+	echo "$(basename "$BASH_SOURCE"): Error on line $1" >&2; exit 1
 }
 
 trap 'handleErr $LINENO' ERR
